{
 "title": "{{display_name}} — GCP Billing Costs",
 "description": "Display your Google Cloud Platform billing costs straight from BigQuery.",
 "tags": [
  "{{project_slug}}",
  "billing",
  "gcp"
 ],
 "time": { "from": "2020-06-01T00:00:00.000Z", "to": "2020-06-30T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "SELECT DISTINCT project.id FROM `$source_table`"
   },
   { "name": "source_project", "label": "Source Project", "query": "{{gcp_project}}" },
   { "name": "source_dataset", "label": "Source Dataset", "query": "billing_export" },
   {
    "name": "source_table",
    "label": "Source Table",
    "query": "SELECT CONCAT(table_catalog, \".\", table_schema, \".\", table_name) FROM `$source_project.$source_dataset.INFORMATION_SCHEMA.TABLES` WHERE REGEXP_CONTAINS(table_name, \"^gcp_billing_export_v1_\")"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "${VAR_DATASET}",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${VAR_PROJECT}",
     "rawSql": "SELECT\n  CURRENT_TIMESTAMP() AS time,\n  SUM(cost) AS value\nFROM\n  `$source_table`\nWHERE\n  $__timeFilter(usage_start_time) AND\n  project.id IN ($project)\nGROUP BY 1\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Project Breakdown",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n  CURRENT_TIMESTAMP() AS time,\n  project.id AS metric,\n  SUM(cost) AS value\nFROM\n  `$source_table`\nWHERE\n  $__timeFilter(usage_start_time)\nGROUP BY 2\nORDER BY 3 DESC"
    }
   ]
  },
  {
   "title": "Top 5 Service Breakdown",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT\n  CURRENT_TIMESTAMP() AS time,\n  IF(pos > 5, 'Other', metric) AS metric,\n  SUM(value) AS value\nFROM (\n  SELECT\n    service.description AS metric,\n    SUM(cost) AS value,\n    ROW_NUMBER() OVER (ORDER BY SUM(cost) DESC) AS pos\n  FROM\n    `$source_table`\n  WHERE\n    $__timeFilter(usage_start_time) AND\n    project.id IN ($project)\n  GROUP BY 1\n)\nGROUP BY 2\nORDER BY metric != 'Other' DESC, 3 DESC"
    }
   ]
  },
  {
   "title": "Service Breakdown",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Cost ($)" }
   ],
   "targets": [
    {
     "dataset": "${VAR_DATASET}",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${VAR_PROJECT}",
     "rawSql": "SELECT *\nFROM (\n  SELECT\n    $__timeGroup(usage_start_time, 1d),\n    service.description AS metric,\n    SUM(cost) AS value\n  FROM\n    `$source_table`\n  WHERE\n    $__timeFilter(usage_start_time) AND project.id IN ($project)\n  GROUP BY 1, 2\n  ORDER BY 1 ASC\n)\nWHERE value > 0"
    }
   ]
  },
  {
   "title": "SKU Breakdown",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "Cost ($)" }
   ],
   "targets": [
    {
     "dataset": "${VAR_DATASET}",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "${VAR_PROJECT}",
     "rawSql": "SELECT * FROM (\n  SELECT\n    $__timeGroup(usage_start_time, 1d),\n    IFNULL(sku.description, '_') AS metric,\n    SUM(cost) AS value\n  FROM `$source_table`\n  WHERE\n    DATE(usage_start_time) >= DATE($__millisTimeFrom(_)) AND\n    DATE(usage_start_time) < DATE($__millisTimeTo(_)) AND\n    project.id IN ($project)\n  GROUP BY 1, 2\n  ORDER BY 1, 2\n)\nWHERE value >= 1"
    }
   ]
  },
  {
   "title": "Breakdown by Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "dataset": "${VAR_DATASET}",
       "orderByCol": "1",
       "orderBySort": "1",
       "project": "${VAR_PROJECT}",
       "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "type": "graph",
     "gridPos": { "h": 12, "w": 17, "x": 7, "y": 8 },
     "yaxes": [
      { "format": "none", "label": "Cost ($)" }
     ],
     "targets": [
      {
       "dataset": "${VAR_DATASET}",
       "orderByCol": "1",
       "orderBySort": "1",
       "project": "${VAR_PROJECT}",
       "rawSql": "-- $__millisTimeFrom(usage_start_time) // $__millisTimeTo(_)\nSELECT\n  $__timeGroupAlias(usage_start_time, 1d),\n  IFNULL(service.description, '_') AS metric,\n  SUM(cost) AS value\nFROM `$table_billing`\nWHERE\n  DATE(usage_start_time) >= DATE($__millisTimeFrom(_)) AND\n  DATE(usage_start_time) < DATE($__millisTimeTo(_)) AND\n  project.id IN ($project)\nGROUP BY 1, 2\nORDER BY 1, 2"
      }
     ]
    }
   ]
  }
 ]
}